"""Added role to User

Revision ID: 80a5f12c95e2
Revises: 88adbba35fb0
Create Date: 2025-07-25 13:59:13.072595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a5f12c95e2'
down_revision = '88adbba35fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_media_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=False),
    sa.Column('current_progress_seconds', sa.Integer(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_media_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_media_progress_media_item_id'), ['media_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_media_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('user_media_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_media_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_media_progress_media_item_id'))

    op.drop_table('user_media_progress')
    # ### end Alembic commands ###
