"""Add thumbnail to MediaItem

Revision ID: 88adbba35fb0
Revises: 80421a15000c
Create Date: 2025-07-24 21:15:11.970214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88adbba35fb0'
down_revision = '80421a15000c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
