"""Add media_type column to media_items table

Revision ID: dfa9e80e1a5e
Revises: 4e42b6583936
Create Date: 2025-06-27 17:58:13.751396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa9e80e1a5e'
down_revision = '4e42b6583936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
